version: '3.9'

services:
  database:
    container_name: pokemon-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    expose:
      - ${DB_PORT}
    networks:
      - pokemon-network
  pokemon-api:
    container_name: pokemon-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    depends_on:
      - database
    networks:
      - pokemon-network
    environment:
      PORT: ${PORT}
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  pokemon-network:
    driver: bridge
